# Generated by Django 4.2.4 on 2024-03-09 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_rename_date_of_birth_author_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=6)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 14, 3, 9, 854045, tzinfo=datetime.timezone.utc)),
        ),
    ]
