# Generated by Django 4.2.4 on 2024-03-09 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_person_alter_author_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='abcd', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 14, 7, 13, 54437, tzinfo=datetime.timezone.utc)),
        ),
    ]
